INSERT INTO categories (category_id, category_name) VALUES (0,'Miscellaneous');
INSERT INTO categories (category_id, category_name) VALUES (1,'Ammo');
INSERT INTO categories (category_id, category_name) VALUES (2,'Arrows');
INSERT INTO categories (category_id, category_name) VALUES (3,'Bolts');
INSERT INTO categories (category_id, category_name) VALUES (4,'Construction materials');
INSERT INTO categories (category_id, category_name) VALUES (5,'Construction products');
INSERT INTO categories (category_id, category_name) VALUES (6,'Cooking ingredients');
INSERT INTO categories (category_id, category_name) VALUES (7,'Costumes');
INSERT INTO categories (category_id, category_name) VALUES (8,'Crafting materials');
INSERT INTO categories (category_id, category_name) VALUES (9,'Familiars');
INSERT INTO categories (category_id, category_name) VALUES (10,'Farming produce');
INSERT INTO categories (category_id, category_name) VALUES (11,'Fletching materials');
INSERT INTO categories (category_id, category_name) VALUES (12,'Food and Drink');
INSERT INTO categories (category_id, category_name) VALUES (13,'Herblore materials');
INSERT INTO categories (category_id, category_name) VALUES (14,'Hunting equipment');
INSERT INTO categories (category_id, category_name) VALUES (15,'Hunting Produce');
INSERT INTO categories (category_id, category_name) VALUES (16,'Jewellery');
INSERT INTO categories (category_id, category_name) VALUES (17,'Mage armour');
INSERT INTO categories (category_id, category_name) VALUES (18,'Mage weapons');
INSERT INTO categories (category_id, category_name) VALUES (19,'Melee armour - low level');
INSERT INTO categories (category_id, category_name) VALUES (20,'Melee armour - mid level');
INSERT INTO categories (category_id, category_name) VALUES (21,'Melee armour - high level');
INSERT INTO categories (category_id, category_name) VALUES (22,'Melee weapons - low level');
INSERT INTO categories (category_id, category_name) VALUES (23,'Melee weapons - mid level');
INSERT INTO categories (category_id, category_name) VALUES (24,'Melee weapons - high level');
INSERT INTO categories (category_id, category_name) VALUES (25,'Mining and Smithing');
INSERT INTO categories (category_id, category_name) VALUES (26,'Potions');
INSERT INTO categories (category_id, category_name) VALUES (27,'Prayer armour');
INSERT INTO categories (category_id, category_name) VALUES (28,'Prayer materials');
INSERT INTO categories (category_id, category_name) VALUES (29,'Range armour');
INSERT INTO categories (category_id, category_name) VALUES (30,'Range weapons');
INSERT INTO categories (category_id, category_name) VALUES (31,'Runecrafting');
INSERT INTO categories (category_id, category_name) VALUES (32,'Runes, Spells and Teleports');
INSERT INTO categories (category_id, category_name) VALUES (33,'Seeds');
INSERT INTO categories (category_id, category_name) VALUES (34,'Summoning scrolls');
INSERT INTO categories (category_id, category_name) VALUES (35,'Tools and containers');
INSERT INTO categories (category_id, category_name) VALUES (36,'Woodcutting product');
INSERT INTO categories (category_id, category_name) VALUES (37,'Pocket items');
INSERT INTO categories (category_id, category_name) VALUES (38,'Stone spirits');
INSERT INTO categories (category_id, category_name) VALUES (39,'Salvage');
INSERT INTO categories (category_id, category_name) VALUES (40,'Firemaking products');
INSERT INTO categories (category_id, category_name) VALUES (41,'Archaeology materials');
